### ISSUE TITLE
what's the result？

### ISSUE THREAD

**Issue by Accool** [sdnr1/EBIM-NLI#1]
I use your code with a result of up to 81.02. The paper is 86. What is your test score?

**Comment by sdnr1** [comment]
The main reason for an inferior result seems to be the negligence of the usage of Dropouts this implementation. My code does not use Dropout, which is not the case in the original paper (the paper mentions usage of Dropout with 0.5 probability). You could try using Dropouts, which would hopefully improve results. Although I am a little skeptical if you could reach an accuracy of 86%, because some other reports mention obtaining an accuracy of about 85.2 using the EBIM model. Here are a couple of examples - 
- https://web.stanford.edu/class/cs224n/reports/2760320.pdf
- https://web.stanford.edu/class/cs224n/reports/2760013.pdf

As far my test results are concerned, I was not even able to reach 75% accuracy due to lack of availability of an high end training machine. I used a GTX 1070 to train the model and could only attain about 74-75% accuracy after an eternity (I don't remember the exact training time but it took me days). Basically I could not train it well so I was not sure how much accuracy the implementation would give.

I have added dropouts in the feed-forward layers as mentioned in the paper. I hope adding Dropouts will give better results.
